"""Added customer name attribute in order model

Revision ID: c0e3ca7e7c78
Revises: d750a2be4b61
Create Date: 2026-08-05 17:47:47.795797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e3ca7e7c78'
down_revision = 'd750a2be4b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False, server_default="ABC Traders"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
