"""Add purchase order and purchase order item

Revision ID: fb5607d6785a
Revises: 87e151a3532d
Create Date: 2026-10-05 14:15:16.159591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5607d6785a'
down_revision = '87e151a3532d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_order_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['purchase_order_id'])
        batch_op.create_foreign_key(None, 'purchase_orders', ['purchase_order_id'], ['purchase_order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('purchase_order_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
